### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by sheljohn** [bmc/pyutmp#4]
Is there any plan to update this package to Python 3?
It seems to be the best utmp wrapper out there, so it would be great to update if possible.

I tried forking, editing with minor changes (mainly with `print` and `raise`), and it seems to build fine.
Installation with `python setup.py install` works too, but then importing `pyutmp` yields the following errror:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/pyutmp/pyutmp/__init__.py", line 306, in <module>
    exec('import pyutmp_%s as _pyutmp' % _get_platform())
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pyutmp_bsd'
```

I assume this has to do with the `setup.py` file  somehow, but I am still relatively new to python, and never made a package before, so I would need a bit of help. FYI the fork can be found [here](https://github.com/sheljohn/pyutmp).

**Comment by bmc** [comment]
Honestly, I haven't used this in years. I'll try to make time to take a look at it.
